@startuml 宏观规划
class "A宏观规划" as A{
    ==最终目标==
    + 制作0-1背包变现动画
    ==拆分目标==
    --初始阶段--
    + 抛出问题,引起思考
    --图形展示--
    + 整体上是树形结构
    + 每点开一个节点,显示uml图
    + 能够清晰展示内部细节
    --动画效果--
    + 跟随算法深入
    + 树形节点放大转换成uml
    + 每生成一个uml缩放看整体
    --附加效果--
    + 代码同步逐行运行 
}

class "B可能需要练习的地方" as B{
    + Transform动画部分
    + Scene缩放部分
    + 动画细节部分
}

class "C拆分抛出问题引起思考" as C{
    + 存在中午文本显示问题
    + 背景设计等不做
    + 细节优化不做(比如小人思考等)
}
@enduml