@startuml 基本步骤
class "宏观步骤" as A{
    ==准备==
    + ①有需求的学习
    + ②制定好目标
    ==计划==
    + ③宏观层面了解
    + ④深度学习
    ==理解记忆==
    + ⑤制作课件
    + ⑥视频讲解
    + ⑦带痛苦的练习
    ==实战==
    + ⑧已学知识层层组合
    + ⑨搭建自己的案例库
    + ⑩模拟考试
    + ⑪拥有推倒重来的勇气
    ==正向反馈==
    + ⑫github提交
    + ⑬博客视频等观众反馈
    + ⑭实战中完成的小项目
    + ⑮学习时间可视化
    ==最终效果==
    + ⑯知道怎么用的就行
    + ⑰忘了看文档就会
    ==复习==
    + ⑱固定时间对某一类别
           内容复习
}

note right of A::② #Pink
短期目标?长期目标?总目标?
学习的时候,时刻想着,这些东西与你的目标期望是否相符
如果偏离航线,及时更正
end note

note right of A::④ #Pink
注意,深度学习的内容,必须以实现目标为前提,
如果毫不相干,不学也罢
end note

note right of A::⑦ #Pink
一般的练习,我们可能就是跟着练,视频或者书上做什么,
我们模仿一边.而痛苦的练习就是提升难度的练习,比如
将源代码直接去掉,直接按照成品自己复现,或者在原有的
基础之上,添加上一些之前学过的东西,形成组合练习,
也可以问一些详细问题,看看以后得自己能否再回答上来
end note
@enduml