@startuml 工具使用
class "工具使用" as A{
    ==随机提示音==
    + ①提示
    ==Clockify==
    + ②提示
    ==待办组件==
    + ③提示
    ==事项清单==
    + ④提示
    ==随机性==
    + ⑤提示
}

note right of A::① #Pink
效果是每5min随机响,持续90min
响后停留10s(休息?冥想?)
90min后需要休息10min-20min,
休息时杜绝手机游戏等
每随机响一下,其实就是一次反馈
end note
note left of A::② #lightskyblue
这个是仿照steam,用来统计我学习
时长的软件.我想了想,steam中游戏
游玩时长,似乎也是一种反馈作用,那么
记录学习时长,不也是一种反馈作用吗?
在我学习Java的时候一直用着,感觉效果
不错.不过对于Python而言,我没有细分,
比如各种包的学习我也归为python.但
现在感觉全都细分开来比较好.
end note

note right of A::③ #Pink
这个是极序中的软件,在我桌面上
说来惭愧,很早就弄了,一直没用,现在也
算是用上了.我觉得只需要统计一下当天
的任务目标就行,按照前面说的,极致地
细分,不能将一个庞大的任务放上去,看一
眼都不想干.
end note

note left of A::④ #LightSkyBlue
这个跟上面的类似,打算存放长期任务
算了,感觉还是需要再仔细划分一下的,
这么简单说说他太草率了.
end note

note right of A::⑤ #Pink
这个是我之前自己写的小软件.因为
之前云顶玩的比较多,前段时候也经
常看云顶直播,所以我就反思,什么让
我这么着迷呢?想来想去,原来是海克
斯.即将刷新的海克斯,一直吸引着我,
总是想会是什么呢?是不是彩?如果不
是彩的话,我会想,下一个会不会是彩?
所以我模拟了这种勾引我的的效果,用
到学习上.不过当时什么都想弄,添加
的东西比较多,劳动节回校之后也就没
再弄了.
end note
@enduml