@startuml 大致规划
start
:首先应明确,你面向的对象是学生,而不是自己;

:回顾一下,目前为止,你学习过的东西(剪辑、C、C++、Java、Python、Latex、Markdown等)
学习方面有什么共同特征,引起你学习的兴趣点是什么,又是什么阻碍了你深入学习.;

:反思一下,为什么想好了如何复盘,如何重复,进行了一段时间过后,却又戛然而止;

:对于这半年了manim的学习,复盘一下,问题出在了哪里;

:上面内容,主要是反思,之后,根据思考摘要中的第二点,作为架构方面的安排;

:架构归架构,具体内容肯定也是需根据后续内容来进行详细地汇总、总结;

:文档内容过多,不太想看.正反馈激励,github中上传文件.目前工具汇总,比如计时软件等.
如何进行理解+记忆呢.避免无效重复,产生痛感.;

:模拟实战,如何模拟实战.有没有推倒重来的勇气?自己创造考试环境;

:设立目标,明确自己要干什么,然后学习相关的内容,就为了专门解决此前目标,不要多学,否则容易枯燥
乏味,漫无目的;

end
@enduml